# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email_fetcher.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'email_fetcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65mail_fetcher.proto\x12\x0c\x65mailfetcher\"B\n\rThreadRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\"S\n\x05\x45mail\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"J\n\x14ThreadEmailsResponse\x12#\n\x06\x65mails\x18\x01 \x03(\x0b\x32\x13.emailfetcher.Email\x12\r\n\x05\x65rror\x18\x02 \x01(\t2i\n\x13\x45mailFetcherService\x12R\n\x0fGetThreadEmails\x12\x1b.emailfetcher.ThreadRequest\x1a\".emailfetcher.ThreadEmailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_fetcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THREADREQUEST']._serialized_start=37
  _globals['_THREADREQUEST']._serialized_end=103
  _globals['_EMAIL']._serialized_start=105
  _globals['_EMAIL']._serialized_end=188
  _globals['_THREADEMAILSRESPONSE']._serialized_start=190
  _globals['_THREADEMAILSRESPONSE']._serialized_end=264
  _globals['_EMAILFETCHERSERVICE']._serialized_start=266
  _globals['_EMAILFETCHERSERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
